### ISSUE TITLE
KeyError issue

### ISSUE THREAD

**Issue by Amajo0209** [MILVLG/openvqa#81]
Hi, I am trying to train the mcan model using gqa dataset, and everytime I try to run, I get the following error:

Traceback (most recent call last):
  File "run.py", line 162, in <module>
    execution.run(__C.RUN_MODE)
  File "D:\VQA_docs\openvqa-master\utils\exec.py", line 33, in run
    train_engine(self.__C, self.dataset, self.dataset_eval)
  File "D:\VQA_docs\openvqa-master\utils\train_engine.py", line 137, in train_engine
    for (step,frcn_feat_iter, grid_feat_iter, bbox_feat_iter, ques_ix_iter, ans_iter) in enumerate(dataloader):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\VQA_docs\openvqa-master\openvqa\core\base_dataset.py", line 36, in __getitem__
    frcn_feat_iter, grid_feat_iter, bbox_feat_iter = self.load_img_feats(idx, iid)
  File "D:\VQA_docs\openvqa-master\openvqa\datasets\gqa\gqa_loader.py", line 204, in load_img_feats
    frcn_feat = np.load(self.iid_to_frcn_feat_path[iid])
KeyError: '2363772'

I was getting some other errors before this one, and I got to solve them. however, the only issue I am struggling with now is this one. DOES ANYONE KNOW HOW I CAN FIX THIS?

**Comment by LSC200107** [comment]
> 嗨，我正在尝试使用gqa数据集训练mcan模型，每次尝试运行时，我都会收到以下错误：
> 
> 回溯（最近一次呼叫）：文件“run.py”，第162行，在execution.run（__C.RUN_MODE）文件“D:\VQA_docs\openvqa-master\utils\exec.py”，第33行，正在运行train_engine（自我。__C，self.dataset，self.dataset_eval）文件“D:\VQA_docs\openvqa-master\utils\train_engine.py”，第137行，在train_engine中对于（步骤，frcn_feat_iter，grid_feat_iter，bbox_feat_iter，ques_ix_iter，ans_iter）在枚举（数据加载器）中：文件“C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py”，第521行，**下一**数据 = self._next_data()文件“C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py”，第1203行，在_next_data中返回self._process_data（数据）文件“C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py”，第1229行，在_process_data中data.reraise（）文件“C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch_utils.py”，第434行，重新提出提高例外KeyError：在DataLoader工作进程0中捕获KeyError。原始回溯（最近一次通话）：文件“C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data_utils\worker.py”，第287行，在_worker_loop中数据 = fetcher.fetch（索引）文件“C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data_utils\fetch.py”，第49行，在获取中data = [self.dataset[idx] for idx in possibly_batched_index]文件“C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data_utils\fetch.py”，第49行，在data = [self.dataset[idx] for idx in possibly_batched_index]文件“D:\VQA_docs\openvqa-master\openvqa\core\base_dataset.py”，第36行，在**getitem中**frcn_feat_iter, grid_feat_iter, bbox_feat_iter = self.load_img_feats(idx, iid)文件“D:\VQA_docs\openvqa-master\openvqa\datasets\gqa\gqa_loader.py”，第204行，在load_img_feats中frcn_feat = np.load(self.iid_to_frcn_feat_path[iid])密钥错误：'2363772'
> 
> 在这之前，我遇到了一些其他错误，我必须解决它们。然而，我现在唯一挣扎的问题就是这个。有人知道我怎样才能解决这个问题吗？



> Hi, I am trying to train the mcan model using gqa dataset, and everytime I try to run, I get the following error:
> 
> Traceback (most recent call last): File "run.py", line 162, in execution.run(__C.RUN_MODE) File "D:\VQA_docs\openvqa-master\utils\exec.py", line 33, in run train_engine(self.__C, self.dataset, self.dataset_eval) File "D:\VQA_docs\openvqa-master\utils\train_engine.py", line 137, in train_engine for (step,frcn_feat_iter, grid_feat_iter, bbox_feat_iter, ques_ix_iter, ans_iter) in enumerate(dataloader): File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 521, in **next** data = self._next_data() File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data return self._process_data(data) File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data data.reraise() File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch_utils.py", line 434, in reraise raise exception KeyError: Caught KeyError in DataLoader worker process 0. Original Traceback (most recent call last): File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data_utils\worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\VQA_docs\openvqa-master\openvqa\core\base_dataset.py", line 36, in **getitem** frcn_feat_iter, grid_feat_iter, bbox_feat_iter = self.load_img_feats(idx, iid) File "D:\VQA_docs\openvqa-master\openvqa\datasets\gqa\gqa_loader.py", line 204, in load_img_feats frcn_feat = np.load(self.iid_to_frcn_feat_path[iid]) KeyError: '2363772'
> 
> I was getting some other errors before this one, and I got to solve them. however, the only issue I am struggling with now is this one. DOES ANYONE KNOW HOW I CAN FIX THIS?

Hello, have you solved this problem? I encountered the same problem. Thanks

**Comment by LSC200107** [comment]
> Hi, I am trying to train the mcan model using gqa dataset, and everytime I try to run, I get the following error:
> 
> Traceback (most recent call last): File "run.py", line 162, in execution.run(__C.RUN_MODE) File "D:\VQA_docs\openvqa-master\utils\exec.py", line 33, in run train_engine(self.__C, self.dataset, self.dataset_eval) File "D:\VQA_docs\openvqa-master\utils\train_engine.py", line 137, in train_engine for (step,frcn_feat_iter, grid_feat_iter, bbox_feat_iter, ques_ix_iter, ans_iter) in enumerate(dataloader): File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 521, in **next** data = self._next_data() File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data return self._process_data(data) File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data data.reraise() File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch_utils.py", line 434, in reraise raise exception KeyError: Caught KeyError in DataLoader worker process 0. Original Traceback (most recent call last): File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data_utils\worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\VQA_docs\openvqa-master\openvqa\core\base_dataset.py", line 36, in **getitem** frcn_feat_iter, grid_feat_iter, bbox_feat_iter = self.load_img_feats(idx, iid) File "D:\VQA_docs\openvqa-master\openvqa\datasets\gqa\gqa_loader.py", line 204, in load_img_feats frcn_feat = np.load(self.iid_to_frcn_feat_path[iid]) KeyError: '2363772'
> 
> I was getting some other errors before this one, and I got to solve them. however, the only issue I am struggling with now is this one. DOES ANYONE KNOW HOW I CAN FIX THIS?

Hello, have you solved this problem?I encountered the same problem.

**Comment by J-Luuu** [comment]
【自动回复】您好，已收到邮件！This is an automatic reply, confirming that your e-mail was received. Thank you!
